version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=swapi
      - POSTGRES_USER=swapiuser
      - POSTGRES_PASSWORD=swapipassword

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"

  celery_worker:
    build: .
    command: celery -A swapi_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - db
      - redis

  # flower:
  #   image: mher/flower
  #   command: flower -A swapi_app --port=5555 --broker=redis://redis:6379/0
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - redis

volumes:
  postgres_data:
